=== api-evangelist/zoom/json-schema/zoom-meeting-registrant-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Registrant",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "description": "Registrant ID."
    },
    "email": {
      "type": "string",
      "description": "Registrant email address."
    },
    "first_name": {
      "type": "string",
      "description": "Registrant first name."
    },
    "last_name": {
      "type": "string",
      "description": "Registrant last name."
    },
    "address": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "state": {
      "type": "string"
    },
    "zip": {
      "type": "string"
    },
    "country": {
      "type": "string"
    },
    "phone": {
      "type": "string"
    },
    "industry": {
      "type": "string"
    },
    "org": {
      "type": "string"
    },
    "job_title": {
      "type": "string"
    },
    "purchasing_time_frame": {
      "type": "string"
    },
    "role_in_purchase_process": {
      "type": "string"
    },
    "no_of_employees": {
      "type": "string"
    },
    "comments": {
      "type": "string"
    },
    "status": {
      "type": "string",
      "description": "Registrant status."
    },
    "create_time": {
      "type": "string",
      "description": "Time the registrant registered."
    },
    "join_url": {
      "type": "string",
      "description": "Unique join URL for this registrant."
    }
  }
}

=== api-evangelist/zoom/examples/zoom-meeting-registrant-example.json
{
  "id": "abc123",
  "email": "user@example.com",
  "first_name": "example_value",
  "last_name": "example_value",
  "address": "example_value",
  "city": "example_value",
  "state": "example_value",
  "zip": "example_value",
  "country": "example_value",
  "phone": "example_value",
  "industry": "example_value",
  "org": "example_value",
  "job_title": "example_value",
  "purchasing_time_frame": "example_value",
  "role_in_purchase_process": "example_value",
  "no_of_employees": "example_value",
  "comments": "example_value",
  "status": "example_value",
  "create_time": "example_value",
  "join_url": "https://www.example.com"
}
